[package]
name = "pymers"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.12"
axum-extra = { path = "../../axum/axum-extra" , features = ["typed-header"] }
chrono = { version = "0.4.24", features = ["serde"] }
dotenv = "0.15.0"
jsonwebtoken = "8.3.0"
once_cell = "1.18.0"
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
sqlx = { version = "0.6.3", features = ["runtime-async-std-native-tls", "postgres", "chrono", "uuid"] }
tokio = { version = "1.27.0", features = ["full"] }
tower-http = { version = "0.4.0", features = ["cors"] }
