"""additional

Revision ID: 16336fdcf149
Revises: b19219500f48
Create Date: 2023-09-15 09:35:49.619429

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '16336fdcf149'
down_revision = 'b19219500f48'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roomtype', sa.Column('additional_usd', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('roomtype', sa.Column('additional_ars', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('roomtype', sa.Column('single_usd', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('roomtype', sa.Column('single_ars', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roomtype', 'single_ars')
    op.drop_column('roomtype', 'single_usd')
    op.drop_column('roomtype', 'additional_ars')
    op.drop_column('roomtype', 'additional_usd')
    # ### end Alembic commands ###
