"""booking

Revision ID: 236039c35ecc
Revises: 079c83aa0016
Create Date: 2023-09-16 17:18:53.509096

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '236039c35ecc'
down_revision = '079c83aa0016'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('room_id', sa.Integer(), nullable=True))
    op.add_column('booking', sa.Column('checkin_t', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('booking', sa.Column('checkout_t', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('booking', sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('booking', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.create_foreign_key(None, 'booking', 'room', ['room_id'], ['id'])
    op.drop_column('booking', 'arrival_t')
    op.drop_column('booking', 'arrival')
    op.drop_column('booking', 'ars')
    op.drop_column('booking', 'usd')
    op.drop_column('booking', 'departure')
    op.drop_column('booking', 'departure_t')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('departure_t', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('booking', sa.Column('departure', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('booking', sa.Column('usd', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('booking', sa.Column('ars', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('booking', sa.Column('arrival', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('booking', sa.Column('arrival_t', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.drop_column('booking', 'price')
    op.drop_column('booking', 'currency')
    op.drop_column('booking', 'checkout_t')
    op.drop_column('booking', 'checkin_t')
    op.drop_column('booking', 'room_id')
    # ### end Alembic commands ###
