"""config

Revision ID: b19219500f48
Revises: 
Create Date: 2023-09-11 18:25:47.319308

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'b19219500f48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('usd', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('booking', sa.Column('ars', sa.Numeric(precision=10, scale=2), nullable=True))
    op.drop_column('booking', 'price_ars')
    op.drop_column('booking', 'price_usd')
    op.add_column('config', sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('config', sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_config_key'), 'config', ['key'], unique=True)
    op.create_index(op.f('ix_config_value'), 'config', ['value'], unique=False)
    op.drop_column('config', 'breakfast_price_usd')
    op.drop_column('config', 'breakfast_price_ars')
    op.add_column('price', sa.Column('usd', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('price', sa.Column('ars', sa.Numeric(precision=10, scale=2), nullable=True))
    op.drop_column('price', 'price_ars')
    op.drop_column('price', 'price_usd')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price', sa.Column('price_usd', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('price', sa.Column('price_ars', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_column('price', 'ars')
    op.drop_column('price', 'usd')
    op.add_column('config', sa.Column('breakfast_price_ars', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('config', sa.Column('breakfast_price_usd', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_config_value'), table_name='config')
    op.drop_index(op.f('ix_config_key'), table_name='config')
    op.drop_column('config', 'value')
    op.drop_column('config', 'key')
    op.add_column('booking', sa.Column('price_usd', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('booking', sa.Column('price_ars', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_column('booking', 'ars')
    op.drop_column('booking', 'usd')
    # ### end Alembic commands ###
