# name: Rust Build
# on:
#   push:
#     branches:
#       - main
# env:
#   CARGO_TERM_COLOR: always
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     working-directory: rs
#     steps:
#       - uses: actions/checkout@v3
#       - name: Build
#         run: cargo build --verbose
#       - name: Run tests
#         run: cargo test --verbose
